/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pvergara' at '12/29/16 11:06 PM' with Gradle 3.2
 *
 * @author pvergara, @date 12/29/16 11:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
